bind_address = ":8080"
log_level = "debug"

[StorageConfig]
database_url = "host=localhost dbname=postgres user=postgres password=123 sslmode=disable"

[NotifierConfig]
mailer_daemon = "smtp.yandex.ru"
mailer_daemon_port = 25
